################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/ST/touchUI_Development/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/port.c \
C:/ST/touchUI_Development/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/portasm.c 

C_DEPS += \
./Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/port.d \
./Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/portasm.d 

OBJS += \
./Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/port.o \
./Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/portasm.o 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/port.o: C:/ST/touchUI_Development/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/port.c Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N645xx -c -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/Core/Inc" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/Middlewares/ST/touchgfx/framework/include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/Middlewares/ST/touchgfx/lib/core/cortex_m55/gcc" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/TouchGFX/App" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/Drivers/i2cCustomeDriver/inc" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/Drivers/i2cCustomeDriver/src" -I"C:/ST/touchUI_Development/touchUI_Bringup/Drivers/CMSIS/Include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/TouchGFX/App" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/TouchGFX/target/generated" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/TouchGFX/target" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/Core/Inc" -I"C:/ST/touchUI_Development/touchUI_Bringup/Secure_nsclib" -I"C:/ST/touchUI_Development/touchUI_Bringup/Drivers/STM32N6xx_HAL_Driver/Inc" -I"C:/ST/touchUI_Development/touchUI_Bringup/Drivers/CMSIS/Device/ST/STM32N6xx/Include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy" -I"C:/ST/touchUI_Development/touchUI_Bringup/Drivers/CMSIS/Include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure" -I"C:/ST/touchUI_Development/touchUI_Bringup/Middlewares/Third_Party/CMSIS/RTOS2/Include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/Middlewares/ST/touchgfx/framework/include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/TouchGFX/generated/fonts/include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/TouchGFX/generated/gui_generated/include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/TouchGFX/generated/images/include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/TouchGFX/generated/texts/include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/TouchGFX/generated/videos/include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/TouchGFX/gui/include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/Middlewares/ST/touchgfx/3rdparty/libjpeg/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/portasm.o: C:/ST/touchUI_Development/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/portasm.c Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N645xx -c -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/Core/Inc" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/Middlewares/ST/touchgfx/framework/include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/Middlewares/ST/touchgfx/lib/core/cortex_m55/gcc" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/TouchGFX/App" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/Drivers/i2cCustomeDriver/inc" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/Drivers/i2cCustomeDriver/src" -I"C:/ST/touchUI_Development/touchUI_Bringup/Drivers/CMSIS/Include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/TouchGFX/App" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/TouchGFX/target/generated" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/TouchGFX/target" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/Core/Inc" -I"C:/ST/touchUI_Development/touchUI_Bringup/Secure_nsclib" -I"C:/ST/touchUI_Development/touchUI_Bringup/Drivers/STM32N6xx_HAL_Driver/Inc" -I"C:/ST/touchUI_Development/touchUI_Bringup/Drivers/CMSIS/Device/ST/STM32N6xx/Include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy" -I"C:/ST/touchUI_Development/touchUI_Bringup/Drivers/CMSIS/Include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure" -I"C:/ST/touchUI_Development/touchUI_Bringup/Middlewares/Third_Party/CMSIS/RTOS2/Include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/Middlewares/ST/touchgfx/framework/include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/TouchGFX/generated/fonts/include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/TouchGFX/generated/gui_generated/include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/TouchGFX/generated/images/include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/TouchGFX/generated/texts/include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/TouchGFX/generated/videos/include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/TouchGFX/gui/include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include" -I"C:/ST/touchUI_Development/touchUI_Bringup/Appli/Middlewares/ST/touchgfx/3rdparty/libjpeg/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-FreeRTOS-2f-Source-2f-portable-2f-GCC-2f-ARM_CM55_NTZ-2f-non_secure

clean-Middlewares-2f-FreeRTOS-2f-Source-2f-portable-2f-GCC-2f-ARM_CM55_NTZ-2f-non_secure:
	-$(RM) ./Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/port.cyclo ./Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/port.d ./Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/port.o ./Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/port.su ./Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/portasm.cyclo ./Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/portasm.d ./Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/portasm.o ./Middlewares/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/portasm.su

.PHONY: clean-Middlewares-2f-FreeRTOS-2f-Source-2f-portable-2f-GCC-2f-ARM_CM55_NTZ-2f-non_secure

