################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/CurrentDevelopment/touchUIPCB/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c \
C:/CurrentDevelopment/touchUIPCB/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
C:/CurrentDevelopment/touchUIPCB/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
C:/CurrentDevelopment/touchUIPCB/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/list.c \
C:/CurrentDevelopment/touchUIPCB/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/port.c \
C:/CurrentDevelopment/touchUIPCB/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/portasm.c \
C:/CurrentDevelopment/touchUIPCB/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/queue.c \
C:/CurrentDevelopment/touchUIPCB/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c \
C:/CurrentDevelopment/touchUIPCB/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
C:/CurrentDevelopment/touchUIPCB/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/timers.c 

C_DEPS += \
./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/cmsis_os2.d \
./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/croutine.d \
./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/event_groups.d \
./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/list.d \
./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/port.d \
./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/portasm.d \
./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/queue.d \
./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/stream_buffer.d \
./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/tasks.d \
./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/timers.d 

OBJS += \
./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/cmsis_os2.o \
./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/croutine.o \
./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/event_groups.o \
./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/list.o \
./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/port.o \
./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/portasm.o \
./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/queue.o \
./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/stream_buffer.o \
./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/tasks.o \
./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/timers.o 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/cmsis_os2.o: C:/CurrentDevelopment/touchUIPCB/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N645xx -c -I../../../Appli/TouchGFX/App -I../../../Appli/TouchGFX/target/generated -I../../../Appli/TouchGFX/target -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/ -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Appli/../../Appli/Middlewares/ST/touchgfx/framework/include -I../../Appli/../../Appli/TouchGFX/generated/fonts/include -I../../Appli/../../Appli/TouchGFX/generated/gui_generated/include -I../../Appli/../../Appli/TouchGFX/generated/images/include -I../../Appli/../../Appli/TouchGFX/generated/texts/include -I../../Appli/../../Appli/TouchGFX/generated/videos/include -I../../Appli/../../Appli/TouchGFX/gui/include -I../../Appli/../../Appli/Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Appli/../../Appli/Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/croutine.o: C:/CurrentDevelopment/touchUIPCB/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/croutine.c Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N645xx -c -I../../../Appli/TouchGFX/App -I../../../Appli/TouchGFX/target/generated -I../../../Appli/TouchGFX/target -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/ -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Appli/../../Appli/Middlewares/ST/touchgfx/framework/include -I../../Appli/../../Appli/TouchGFX/generated/fonts/include -I../../Appli/../../Appli/TouchGFX/generated/gui_generated/include -I../../Appli/../../Appli/TouchGFX/generated/images/include -I../../Appli/../../Appli/TouchGFX/generated/texts/include -I../../Appli/../../Appli/TouchGFX/generated/videos/include -I../../Appli/../../Appli/TouchGFX/gui/include -I../../Appli/../../Appli/Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Appli/../../Appli/Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/event_groups.o: C:/CurrentDevelopment/touchUIPCB/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/event_groups.c Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N645xx -c -I../../../Appli/TouchGFX/App -I../../../Appli/TouchGFX/target/generated -I../../../Appli/TouchGFX/target -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/ -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Appli/../../Appli/Middlewares/ST/touchgfx/framework/include -I../../Appli/../../Appli/TouchGFX/generated/fonts/include -I../../Appli/../../Appli/TouchGFX/generated/gui_generated/include -I../../Appli/../../Appli/TouchGFX/generated/images/include -I../../Appli/../../Appli/TouchGFX/generated/texts/include -I../../Appli/../../Appli/TouchGFX/generated/videos/include -I../../Appli/../../Appli/TouchGFX/gui/include -I../../Appli/../../Appli/Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Appli/../../Appli/Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/list.o: C:/CurrentDevelopment/touchUIPCB/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/list.c Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N645xx -c -I../../../Appli/TouchGFX/App -I../../../Appli/TouchGFX/target/generated -I../../../Appli/TouchGFX/target -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/ -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Appli/../../Appli/Middlewares/ST/touchgfx/framework/include -I../../Appli/../../Appli/TouchGFX/generated/fonts/include -I../../Appli/../../Appli/TouchGFX/generated/gui_generated/include -I../../Appli/../../Appli/TouchGFX/generated/images/include -I../../Appli/../../Appli/TouchGFX/generated/texts/include -I../../Appli/../../Appli/TouchGFX/generated/videos/include -I../../Appli/../../Appli/TouchGFX/gui/include -I../../Appli/../../Appli/Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Appli/../../Appli/Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/port.o: C:/CurrentDevelopment/touchUIPCB/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/port.c Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N645xx -c -I../../../Appli/TouchGFX/App -I../../../Appli/TouchGFX/target/generated -I../../../Appli/TouchGFX/target -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/ -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Appli/../../Appli/Middlewares/ST/touchgfx/framework/include -I../../Appli/../../Appli/TouchGFX/generated/fonts/include -I../../Appli/../../Appli/TouchGFX/generated/gui_generated/include -I../../Appli/../../Appli/TouchGFX/generated/images/include -I../../Appli/../../Appli/TouchGFX/generated/texts/include -I../../Appli/../../Appli/TouchGFX/generated/videos/include -I../../Appli/../../Appli/TouchGFX/gui/include -I../../Appli/../../Appli/Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Appli/../../Appli/Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/portasm.o: C:/CurrentDevelopment/touchUIPCB/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/portasm.c Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N645xx -c -I../../../Appli/TouchGFX/App -I../../../Appli/TouchGFX/target/generated -I../../../Appli/TouchGFX/target -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/ -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Appli/../../Appli/Middlewares/ST/touchgfx/framework/include -I../../Appli/../../Appli/TouchGFX/generated/fonts/include -I../../Appli/../../Appli/TouchGFX/generated/gui_generated/include -I../../Appli/../../Appli/TouchGFX/generated/images/include -I../../Appli/../../Appli/TouchGFX/generated/texts/include -I../../Appli/../../Appli/TouchGFX/generated/videos/include -I../../Appli/../../Appli/TouchGFX/gui/include -I../../Appli/../../Appli/Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Appli/../../Appli/Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/queue.o: C:/CurrentDevelopment/touchUIPCB/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/queue.c Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N645xx -c -I../../../Appli/TouchGFX/App -I../../../Appli/TouchGFX/target/generated -I../../../Appli/TouchGFX/target -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/ -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Appli/../../Appli/Middlewares/ST/touchgfx/framework/include -I../../Appli/../../Appli/TouchGFX/generated/fonts/include -I../../Appli/../../Appli/TouchGFX/generated/gui_generated/include -I../../Appli/../../Appli/TouchGFX/generated/images/include -I../../Appli/../../Appli/TouchGFX/generated/texts/include -I../../Appli/../../Appli/TouchGFX/generated/videos/include -I../../Appli/../../Appli/TouchGFX/gui/include -I../../Appli/../../Appli/Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Appli/../../Appli/Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/stream_buffer.o: C:/CurrentDevelopment/touchUIPCB/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N645xx -c -I../../../Appli/TouchGFX/App -I../../../Appli/TouchGFX/target/generated -I../../../Appli/TouchGFX/target -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/ -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Appli/../../Appli/Middlewares/ST/touchgfx/framework/include -I../../Appli/../../Appli/TouchGFX/generated/fonts/include -I../../Appli/../../Appli/TouchGFX/generated/gui_generated/include -I../../Appli/../../Appli/TouchGFX/generated/images/include -I../../Appli/../../Appli/TouchGFX/generated/texts/include -I../../Appli/../../Appli/TouchGFX/generated/videos/include -I../../Appli/../../Appli/TouchGFX/gui/include -I../../Appli/../../Appli/Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Appli/../../Appli/Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/tasks.o: C:/CurrentDevelopment/touchUIPCB/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/tasks.c Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N645xx -c -I../../../Appli/TouchGFX/App -I../../../Appli/TouchGFX/target/generated -I../../../Appli/TouchGFX/target -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/ -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Appli/../../Appli/Middlewares/ST/touchgfx/framework/include -I../../Appli/../../Appli/TouchGFX/generated/fonts/include -I../../Appli/../../Appli/TouchGFX/generated/gui_generated/include -I../../Appli/../../Appli/TouchGFX/generated/images/include -I../../Appli/../../Appli/TouchGFX/generated/texts/include -I../../Appli/../../Appli/TouchGFX/generated/videos/include -I../../Appli/../../Appli/TouchGFX/gui/include -I../../Appli/../../Appli/Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Appli/../../Appli/Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/timers.o: C:/CurrentDevelopment/touchUIPCB/touchUI_Bringup/Middlewares/Third_Party/FreeRTOS/Source/timers.c Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N645xx -c -I../../../Appli/TouchGFX/App -I../../../Appli/TouchGFX/target/generated -I../../../Appli/TouchGFX/target -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Include -I../../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/ -I../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Appli/../../Appli/Middlewares/ST/touchgfx/framework/include -I../../Appli/../../Appli/TouchGFX/generated/fonts/include -I../../Appli/../../Appli/TouchGFX/generated/gui_generated/include -I../../Appli/../../Appli/TouchGFX/generated/images/include -I../../Appli/../../Appli/TouchGFX/generated/texts/include -I../../Appli/../../Appli/TouchGFX/generated/videos/include -I../../Appli/../../Appli/TouchGFX/gui/include -I../../Appli/../../Appli/Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Appli/../../Appli/Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-RTOS2-2f-CMSIS-2f-RTOS2-2f-Core-2f-TZ_Secure_Only

clean-Middlewares-2f-RTOS2-2f-CMSIS-2f-RTOS2-2f-Core-2f-TZ_Secure_Only:
	-$(RM) ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/cmsis_os2.cyclo ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/cmsis_os2.d ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/cmsis_os2.o ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/cmsis_os2.su ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/croutine.cyclo ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/croutine.d ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/croutine.o ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/croutine.su ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/event_groups.cyclo ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/event_groups.d ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/event_groups.o ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/event_groups.su ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/list.cyclo ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/list.d ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/list.o ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/list.su ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/port.cyclo ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/port.d ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/port.o ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/port.su ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/portasm.cyclo ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/portasm.d ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/portasm.o ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/portasm.su ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/queue.cyclo ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/queue.d ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/queue.o ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/queue.su ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/stream_buffer.cyclo ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/stream_buffer.d ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/stream_buffer.o ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/stream_buffer.su ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/tasks.cyclo ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/tasks.d ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/tasks.o ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/tasks.su ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/timers.cyclo ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/timers.d ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/timers.o ./Middlewares/RTOS2/CMSIS/RTOS2/Core/TZ_Secure_Only/timers.su

.PHONY: clean-Middlewares-2f-RTOS2-2f-CMSIS-2f-RTOS2-2f-Core-2f-TZ_Secure_Only

